version: '3'
services:
  tplink-tapo-exporter:
    build: .
    ports:
      - 9235:9235
    restart: unless-stopped
    environment:
      TAPO_EMAIL: "${TAPO_EMAIL}"
      TAPO_PASSWORD: "${TAPO_PASSWORD}"
